export const dummyRecipes = [
    {
      id: '1',
      name: 'Jjajangmyeon',
      image: 'https://www.seriouseats.com/thmb/PCzXtyCf4soYJUhwl7XeW61JinU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2019__04__20190403-black-day-jajangmyeon-joel-russo-1-0b9c401ab7044054bf1c12c03a617fee.jpg',
      ingredients: ['Mi tepung gandum', 'Daging ayam atau sapi', 'Bawang bombay', 'Kecap hitam (chunjang)', 'Minyak wijen', 'Air', 'Gula', 'Garam'],
      steps: [
        'Tumis bawang bombay dengan minyak wijen hingga harum.',
        'Tambahkan daging ayam atau sapi, masak hingga berubah warna.',
        'Masukkan kecap hitam (chunjang), gula, garam, dan air, masak hingga saus mengental.',
        'Rebus mi tepung gandum sesuai petunjuk kemasan, tiriskan.',
        'Campurkan mi dengan saus jjajang dan aduk rata.',
        'Sajikan panas.',
      ],
    },
    {
      id: '2',
      name: 'Gimbap',
      image: 'https://www.seriouseats.com/thmb/WtcBGMWbdUcAIVe8zg4VCm2aqc4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2020__01__20200122-gimbap-vicky-wasik-24-f5ed1075f35846a29e0812ee053a1bf8.jpg',
      ingredients: ['Nasi putih', 'Nori (rumput laut)', 'Telur', 'Wortel', 'Timun', 'Daging ayam atau tuna', 'Minyak wijen'],
      steps: [
        'Masak nasi dan campurkan sedikit minyak wijen dan garam.',
        'Goreng telur dadar tipis dan potong panjang.',
        'Potong wortel dan timun menjadi panjang.',
        'Siapkan nori, ratakan nasi di atasnya, dan tambahkan telur, wortel, timun, dan daging.',
        'Gulung nori dengan rapat, potong-potong dan sajikan.',
      ],
    },
    {
      id: '3',
      name: 'Tteokbokki',
      image: 'https://i.pinimg.com/736x/93/c8/24/93c824ae1045647fce0a8a3b4f569d61.jpg',  
      ingredients: ['Tteok (kue beras)', 'Gochujang', 'Gula', 'Bawang Putih', 'Telur'],
      steps: [
        'Rebus tteok dalam air mendidih hingga empuk.',
        'Tumis bawang putih dengan gochujang hingga harum.',
        'Tambahkan gula dan air, aduk rata.',
        'Masukkan tteok, masak hingga bumbu meresap dan sajikan.',
      ],
    },
    {
      id: '4',
      name: 'Bibimbap',
      image: 'https://www.finnafood.com/blog/wp-content/uploads/2024/05/resep-bibimbap-1.jpg', 
      ingredients: ['Nasi putih', 'Sayuran (bayam, zucchini, wortel)', 'Daging (bulgogi atau ayam)', 'Telur', 'Gochujang', 'Minyak wijen'],
      steps: [
        'Rebus atau tumis sayuran (bayam, zucchini, wortel).',
        'Masak daging (bulgogi atau ayam) sesuai selera.',
        'Goreng telur setengah matang.',
        'Susun nasi dalam mangkuk, lalu tambahkan sayuran, daging, dan telur di atasnya.',
        'Tambahkan gochujang dan minyak wijen.',
        'Aduk rata sebelum disajikan.',
      ],
    },
    {
      id: '5',
      name: 'Kimchi Jjigae',
      image: 'https://www.koreanbapsang.com/wp-content/uploads/2014/03/DSC_5089-3.jpg',
      ingredients: ['Kimchi', 'Daging Sapi', 'Tahu', 'Bawang Putih', 'Gochujang', 'Bawang Bombai'],
      steps: [
        'Tumis bawang bombai dan bawang putih hingga harum.',
        'Tambahkan daging sapi, masak hingga berubah warna.',
        'Masukkan kimchi dan gochujang, aduk rata.',
        'Tambahkan air dan masak hingga mendidih.',
        'Masukkan tahu dan masak hingga semua bahan matang.',
        'Sajikan kimchi jjigae panas dengan nasi putih.',
      ],
    },
    {
      id: '6',
      name: 'Bulgogi',
      image: 'https://assets.bonappetit.com/photos/57acd741f1c801a1038bc801/1:1/w_2560%2Cc_limit/basic-bulgogi.jpg',
      ingredients: ['Daging Sapi', 'Kecap', 'Gula', 'Bawang Putih', 'Bawang Bombai', 'Minyak Wijen'],
      steps: [
        'Potong daging sapi tipis-tipis.',
        'Campurkan kecap, gula, bawang putih, minyak wijen, dan bawang bombai untuk bumbu marinasi.',
        'Masukkan daging sapi ke dalam bumbu dan diamkan selama 30 menit.',
        'Tumis daging sapi yang telah dimarinasi hingga matang.',
        'Sajikan bulgogi dengan nasi putih atau selada.',
      ],
    },
    {
      id: '7',
      name: 'Korean Fried Chicken',
      image: 'https://beyondsweetandsavory.com/wp-content/uploads/2022/02/Korean-fried-chicken-wings-VyTran-7.jpg', 
      ingredients: ['Ayam (bagian sayap atau paha)', 'Tepung terigu', 'Tepung maizena', 'Bawang putih', 'Jahe', 'Gochujang', 'Madu', 'Garam', 'Minyak goreng'],
      steps: [
        'Cuci ayam dan keringkan, kemudian lumuri dengan campuran tepung terigu, tepung maizena, dan garam.',
        'Goreng ayam dalam minyak panas hingga garing dan matang sempurna.',
        'Tumis bawang putih dan jahe dengan sedikit minyak, tambahkan gochujang, madu, dan sedikit air, aduk hingga saus mengental.',
        'Celupkan ayam yang sudah digoreng ke dalam saus, pastikan terbalut rata.',
        'Sajikan ayam goreng Korea dengan taburan wijen dan irisan daun bawang, nikmati dengan nasi putih.',
      ],
    },
    {
      id: '8',
      name: 'Ganjang Gejang',
      image: 'https://static.cdntap.com/tap-assets-prod/wp-content/uploads/sites/24/2022/05/Ganjang-Gejang-Lead.jpg',
      ingredients: ['Kepiting', 'Kecap asin', 'Gula', 'Bawang putih', 'Jahe', 'Gochugaru', 'Minyak wijen'],
      steps: [
        'Cuci kepiting dengan bersih, pastikan bagian cangkang terbuka.',
        'Campurkan kecap asin, gula, bawang putih, jahe, gochugaru, dan minyak wijen untuk membuat saus marinasi.',
        'Masukkan kepiting ke dalam saus dan diamkan selama beberapa hari agar kepiting terfermentasi dengan baik.',
        'Sajikan kepiting yang sudah difermentasi dengan nasi putih.',
      ],
    },
    {
      id: '9',
      name: 'Banchan',
      image: 'https://static.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/p3/102/2024/11/15/a18d364b67b48e427ed9d31715d835d3-4036728550.jpg',
      ingredients: ['Kimchi', 'Sayuran (bayam, selada, zucchini)', 'Tahu', 'Bawang putih', 'Minyak wijen', 'Bumbu kecap'],
      steps: [
        'Siapkan berbagai jenis sayuran dan bahan lainnya untuk membuat banchan.',
        'Rebus atau tumis sayuran, seperti bayam atau zucchini.',
        'Siapkan kimchi atau hidangan fermentasi lainnya.',
        'Susun berbagai banchan dalam piring-piring kecil.',
        'Sajikan banchan sebagai lauk pendamping bersama nasi putih.',
      ],
    },
    {
      id: '10',
      name: 'Japchae',
      image: 'https://www.hungertaskforce.org/wp-content/uploads/2023/11/vegan-japchae-683x1024-1.jpg',
      ingredients: ['Mi kaca (dangmyeon)', 'Daging sapi', 'Bayam', 'Wortel', 'Jamur shiitake', 'Bawang bombay', 'Minyak wijen', 'Gula', 'Kecap asin', 'Gochujang'],
      steps: [
        'Rebus mi kaca (dangmyeon) hingga empuk, tiriskan dan sisihkan.',
        'Tumis daging sapi dengan sedikit minyak hingga matang.',
        'Tumis bawang bombay, wortel, bayam, dan jamur shiitake hingga layu.',
        'Campurkan mi kaca dengan sayuran dan daging sapi yang sudah ditumis.',
        'Tambahkan kecap asin, gula, minyak wijen, dan gochujang, aduk rata.',
        'Sajikan Japchae panas atau dingin sesuai selera.',
      ],
    },
  ];
  